// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr5fLqpno7X1B0jgA-X9lH6SZ81Klnkts',
    appId: '1:899625540994:web:595594a9f8df8d3619039b',
    messagingSenderId: '899625540994',
    projectId: 'bookmate-2c581',
    authDomain: 'bookmate-2c581.firebaseapp.com',
    storageBucket: 'bookmate-2c581.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD32TkrQWQHKLC03LOkhf_48Hn0C_wbOE0',
    appId: '1:899625540994:android:3e1bb94d4180f94219039b',
    messagingSenderId: '899625540994',
    projectId: 'bookmate-2c581',
    storageBucket: 'bookmate-2c581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfGTHxtrLXw-ASpBXH33e4QsPEnVGsCZY',
    appId: '1:899625540994:ios:2eb62a60b77a66e719039b',
    messagingSenderId: '899625540994',
    projectId: 'bookmate-2c581',
    storageBucket: 'bookmate-2c581.firebasestorage.app',
    iosBundleId: 'com.example.bookmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfGTHxtrLXw-ASpBXH33e4QsPEnVGsCZY',
    appId: '1:899625540994:ios:2eb62a60b77a66e719039b',
    messagingSenderId: '899625540994',
    projectId: 'bookmate-2c581',
    storageBucket: 'bookmate-2c581.firebasestorage.app',
    iosBundleId: 'com.example.bookmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr5fLqpno7X1B0jgA-X9lH6SZ81Klnkts',
    appId: '1:899625540994:web:9ca212086494671119039b',
    messagingSenderId: '899625540994',
    projectId: 'bookmate-2c581',
    authDomain: 'bookmate-2c581.firebaseapp.com',
    storageBucket: 'bookmate-2c581.firebasestorage.app',
  );
}
